#!/bin/bash

# Load resources
xrdb -merge .Xresources

# Set the background color
xsetroot -solid black

# Set up an icon tray
trayer --edge top --align right --SetDockType true --SetPartialStrut true \
--expand true --width 10 --transparent true --alpha 255 --height 24 &

# Fire up apps
#pidgin &
#firefox &
if [ -x /usr/bin/nm-applet ]; then
	nm-applet --sm-disable &
fi
if [ -x /usr/bin/gnome-power-manager ]; then
	sleep 3
	gnome-power-manager &
fi
if [ -x /usr/bin/gnome-settings-daemon ]; then
	gnome-settings-daemon &
fi

exec xmonad
